gantt
    title RoboVision diagram Gantta
    dateFormat  YYYY-MM-DD
    todayMarker off
    axisFormat %d-%m
    przegląd materiałów                 :a1, 2021-03-16, 7d
    schemat aplikacji                   :a2, after a1, 7d
    zdobycie niezbędynch informacji     :milestone, m1
    obsługa pada                        :a3, after a2, 7d
    opis komunikacji                    :a4, after a3, 7d
    napisanie sterowania                :a5, after a4, 7d
    komunikacja z robotem               :a6, after a5, 7d
    możliwość zadlengo sterowania       :milestone, m3
            