gantt
    dateFormat  YYYY-MM-DD
    todayMarker off
    axisFormat %d-%m
    prędkościomierz                     :a7, 2021-04-27, 7d
    akcelerometr                        :a8, after a7, 7d
    obiekt 3D                           :a9, after a8, 7d
    żyroskop                            :a10, after a9, 7d
    pełna wizualizacja danych           :milestone, m4
    szukanie błędów                     :a11, after a10, 7d
    ostatnie szlify                     :a12, after a11, 7d
    zakończenie projektu                :milestone, m5

            